name: Generate and publish Github pages
on:
  push:
    branches:
      - main

jobs:
  generate_gh_pages:
    name: generate and publish gh pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - run: nimble docgen
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmldocs
