name: Run tests
on: [push, pull_request]
jobs:
  nimble_test:
    name: nimble test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        nim: ['stable', 'devel']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nimble test -Y
