name: Run tests
on: [push, pull_request]
jobs:
  nimble_test:
    name: nimble test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - run: nimble test -Y
